### ISSUE TITLE
Buffering command handles

### ISSUE THREAD

**Issue by MrCircuit** [inando/adsclient#5]
Hi,

How about buffering command handles? Is this possible or do they change over time? I've only experienced a change after a reconnect.

There's still one possible concurrency issue in the AdsClient class when accessing "activeSymhandles" while changing it. I would like to solve this and additionally include buffering, if possible.

Best regards

**Comment by inando** [comment]
Buffering is a good idea, but I would make a property to turn it on/off if needed.
I never needed buffering because I did buffering in my apps. (on startup)
But that has the disadvantage of slow startup.

I don't think the handles change over time.

Thanks for improving this library!
